---
title: "ggplot2 y ploty"
format: html
theme: lux
toc: true
lang: es
---

# Carga de paquetes

```{r}
#| label: carga-paquetes
#| message: false
#| warning: false

library(tidyverse)
library(DT)
library(gapminder)
library(ggthemes)
library(hrbrthemes)
```

# Conjunto de datos

## mpg

```{r}
#| label: tabla-mpg

mpg |>
  select(manufacturer, year, cty, hwy) |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## Diamonds

```{r}
#| label: tabla-diamonds
#| message: false
#| warning: false

diamonds |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## Gapminder

```{r}
#| label: tabla-gapminder
#| message: false
#| warning: false

gapminder |>
  filter(year == 2007) |> # filtro para el año 2007
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

# Ggplot2

```{r}
#| label: ggplot2-01
#| message: false
#| warning: false

ggplot(data = mpg) + geom_point(aes(x = displ, y = hwy))
```

```{r}
#| label: ggplot2-02

mpg |>
  ggplot(aes(x = displ, y = hwy)) +
  geom_point()
```

```{r}
#| label: ggplot2-03
#| message: false
#| warning: false

mpg |>
  ggplot(aes(x = displ, y = hwy, colour = class)) +
  geom_point()
```

```{r}
#| label: ggplot2-04
#| message: false
#| warning: false

mpg |>
  ggplot(aes(x = displ, y = hwy, shape  = class, colour = class)) +
  geom_point()
```

```{r}
#| label: ggplot2-05
#| message: false
#| warning: false

mpg |>
  ggplot(aes(x = displ, y = hwy, shape = class, color = class)) +
  geom_point() +
  scale_shape_manual(values = c(0, 1, 2, 3, 4, 5, 6)) +
  scale_color_manual(values = c("red", "blue", "green", "purple", "orange", "brown", "pink"))
```

```{r}
#| label: ggplot2-06
#| message: false
#| warning: false

gapminder |>
  ggplot(aes(x = gdpPercap, y = lifeExp)) + 
  geom_point()
```

```{r}
#| label: ggplot2-07
#| message: false
#| warning: false

gapminder |>
  filter(year == 2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp)) + 
  geom_point() 
```

```{r}
#| label: ggplot2-08
#| message: false
#| warning: false

gapminder |>
  filter(year == 2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp)) + 
  geom_point() +
  geom_smooth()
```

```{r}
#| label: ggplot2-09
#| message: false
#| warning: false

gapminder |>
  filter(year == 2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp, color = continent)) + 
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
#| label: ggplot2-10
#| message: false
#| warning: false

gapminder |>
  filter(year == 2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp, color = continent)) + 
  geom_point() +
  geom_smooth(method = "lm") +
  ggtitle("Relacion entre PIB per capita y esperanza de vida en 2007") +
  xlab("PIB per capita EEUU ($)") +
  ylab("Esperanza de vida (años)") + 
  labs(color = "Continente")
```
